// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCzmSLHfo6gyseoLCYXCldBwkl4KFRA0',
    appId: '1:730076905563:web:a5e1986c756fc8b4e33f7e',
    messagingSenderId: '730076905563',
    projectId: 'inventory-app-68',
    authDomain: 'inventory-app-68.firebaseapp.com',
    storageBucket: 'inventory-app-68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbBtenQ2zAr0pDCxWbYxn1iUuUzA5kPiY',
    appId: '1:730076905563:android:65065fe204f5a4e7e33f7e',
    messagingSenderId: '730076905563',
    projectId: 'inventory-app-68',
    storageBucket: 'inventory-app-68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5kMahcLapRqLDrCBseBBD4_daL8yBYBw',
    appId: '1:730076905563:ios:4c615cf6204c7eeae33f7e',
    messagingSenderId: '730076905563',
    projectId: 'inventory-app-68',
    storageBucket: 'inventory-app-68.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5kMahcLapRqLDrCBseBBD4_daL8yBYBw',
    appId: '1:730076905563:ios:b317ff8a492c51ede33f7e',
    messagingSenderId: '730076905563',
    projectId: 'inventory-app-68',
    storageBucket: 'inventory-app-68.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
